SET FOREIGN_KEY_CHECKS = 0;

LOAD DATA LOCAL INFILE './prime-offices.csv' 
REPLACE INTO TABLE Offices
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n';

SHOW WARNINGS LIMIT 10;
SET FOREIGN_KEY_CHECKS = 1;


